workflows:
  mobile-su-report-bot-ci:
    name: Mobile Su Report Bot CI
    max_build_duration: 10
    environment:
      groups:
        - mobile
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Set up virtual environment
        script: |
          python3 -m venv venv
          . venv/bin/activate
      - name: Install dependencies
        script: |
          pip install -r requirements.txt
      - name: Run main script
        script: |
          python3 main.py

  mobile-weekly-report-ci:
    name: Mobile Weekly Report CI
    max_build_duration: 10
    environment:
      groups:
        - mobile
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Set up virtual environment
        script: |
          python3 -m venv venv
          . venv/bin/activate
      - name: Install dependencies
        script: |
          pip install -r requirements.txt
      - name: Run weekly report script
        script: |
          python3 gen_weekly_report.py
